In [1]:
from main import scan_text

# maroon 5 lyrics of payphone
text = """
I'm at a payphone, trying to call home
All of my change I spent on you
Where have the times gone? Baby, it's all wrong
Where are the plans we made for two?
Yeah, I, I know it's hard to remember
The people we used to be
It's even harder to picture
That you're not here next to me
You say it's too late to make it
But is it too late to try?
And in our time that you wasted
All of our bridges burned down
I've wasted my nights
You turned out the lights
Now, I'm paralyzed
Still stuck in that time
When we called it love
But even the sun sets in paradise
I'm at a payphone, trying to call home
All of my change I spent on you
Where have the times gone? Baby, it's all wrong
Where are the plans we made for two?
If "Happy Ever After" did exist
I would still be holding you like this
All those fairy tales are full of shit
One more fucking love song, I'll be sick (oh)
You turned your back on tomorrow
'Cause you forgot yesterday
I gave you my love to borrow
But you just gave it away
You can't expect me to be fine
I don't expect you to care
I know I've said it before
But all of our bridges burned down
I've wasted my nights
You turned out the lights
Now, I'm paralyzed
Still stuck in that time
When we called it love
But even the sun sets in paradise
I'm at a payphone, trying to call home
All of my change I spent on you (oh, oh)
Where have the times gone? Baby, it's all wrong
Where are the plans we made for two? (Yeah)
If "Happy Ever After" did exist
I would still be holding you like this
And all those fairy tales are full of shit
One more fucking love song, I'll be sick (uh)
Now, I'm at a payphone
Man, fuck that shit
I'll be out spending all this money while you sitting 'round
Wondering why it wasn't you who came up from nothing
Made it from the bottom, now, when you see me, I'm stunning
And all of my cars start with a push of a button
Telling me had chances I blew up or whatever you call it
Switch the number to my phone, so you never could call it
Don't need my name on my show, you can tell that I'm balling
Swish, what a shame could have got picked
Had a really good game, but you missed your last shot
So you talk about who you see at the top
Or what you could've saw, but sad to say, it's over for
Phantom pulled up, valet open doors
Wished I'd go away, got what you was looking for
Now, it's me who they want, so you can go
And take that little piece of shit with you
I'm at a payphone, trying to call home
All of my change I spent on you (woo)
Where have the times gone? Baby, it's all wrong
Where are the plans we made for two? (Yeah, yeah)
If "Happy Ever After" did exist (oh, yeah)
I would still be holding you like this
All these fairy tales are full of shit
Yeah, one more fvcking love song, I'll be sick (yeah)
Now, I'm at a payphone
"""

result = scan_text(text, distance=4)

In [2]:
import pandas as pd
df = pd.DataFrame.from_records(result, columns=["lemma", "word", "start", "end", "profanity", "edit_distance"])
print(df)

       lemma     word  start   end profanity  edit_distance
0     called   called    503   509   bellend              3
1     called   called    503   509     abeed              3
2     called   called    503   509    coolie              4
3     called   called    503   509       ape              4
4     called   called    503   509      hell              4
..       ...      ...    ...   ...       ...            ...
149   pulled   pulled   2224  2230     punta              4
150   pulled   pulled   2224  2230    pecker              4
151  fvcking  fvcking   2698  2705     chink              4
152  fvcking  fvcking   2698  2705    vagina              4
153  fvcking  fvcking   2698  2705      fuck              4

[154 rows x 6 columns]

In [3]:
df[df['profanity'] == 'fuck']

       lemma     word  start   end profanity  edit_distance
50   fucking  fucking    827   834      fuck              3
51   fucking  fucking   1544  1551      fuck              3
114       uh       uh   1577  1579      fuck              3
115     fuck     fuck   1609  1613      fuck              0
153  fvcking  fvcking   2698  2705      fuck              4

In [4]:
from data import en_dictionary
'plans' in en_dictionary

False

In [5]:
df[df['profanity'] == 'fuck']

       lemma     word  start   end profanity  edit_distance
50   fucking  fucking    827   834      fuck              3
51   fucking  fucking   1544  1551      fuck              3
114       uh       uh   1577  1579      fuck              3
115     fuck     fuck   1609  1613      fuck              0
153  fvcking  fvcking   2698  2705      fuck              4

In [6]:
# Counting numbers
df[df['word'] == 'one']

Empty DataFrame
Columns: [lemma, word, start, end, profanity, edit_distance]
Index: []

In [7]:
df[df['word'] == 'fvcking']

       lemma     word  start   end profanity  edit_distance
151  fvcking  fvcking   2698  2705     chink              4
152  fvcking  fvcking   2698  2705    vagina              4
153  fvcking  fvcking   2698  2705      fuck              4